// Registers the service worker generated by vite-plugin-pwa
// (see vite.config.js). `virtual:pwa-register` is a virtual module the
// plugin injects at build/dev time — it only resolves once
// `vite-plugin-pwa` is installed (npm install), which is expected to
// happen before this app is run.
//
// registerType: 'autoUpdate' (in vite.config.js) means new versions of
// the app take over automatically on the next load, so no "reload to
// update" prompt is wired up here — keeps this additive and simple.
import { registerSW } from 'virtual:pwa-register';

export function initPWA() {
  if (typeof window === 'undefined') return;

  registerSW({
    immediate: true,
    onOfflineReady() {
      console.info('[EdgeJournal] Ready to work offline.');
    },
    onRegisterError(error) {
      console.error('[EdgeJournal] Service worker registration failed:', error);
    },
  });
}
